---
# tasks file for remote-servers
- name: Disable SELinux
  selinux:
    state: disabled
- name: replacing Enforcing into Disabled SElinux
  lineinfile: 
    path: /etc/selinux/config
    regexp: 'SELINUX=enforcing'
    line: 'SELINUX=disabled'
    backrefs: yes
- name: Install podman & venv
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - podman
    - python3
- name: copy files to remote nodes
  copy:
    src: "{{ src }}"
    dest: "{{ dst }}"
    mode: "0775"
    directory_mode: true
- name: Set files permissions
  file:
    dest: "{{ dst }}/rabbitmq"
    mode: "0775"
    owner: root
    group: root
    recurse: true
- name: copy systemd unit files
  copy:
    remote_src: True
    src: "{{ item.src }}"
    dest: "{{ item.dsti }}"
  with_items:
  - {src: "{{ dst }}/{{ inventory_hostname }}/rabbitmq.service", dsti: '/etc/systemd/system'}
  - {src: "{{ dst }}/{{ inventory_hostname }}/systemd-env", dsti: '/etc/sysconfig/rabbitmq'}
- name: authenticate to VMWare tanzu registery
  containers.podman.podman_login:
    username: "{{ tanzu_user }}"
    password: "{{ tanzu_password }}"
    registry: registry.pivotal.io
- name: Pull an image
  containers.podman.podman_image:
    name: registry.pivotal.io/rabbitmq/vmware-tanzu-rabbitmq:1.2.0
- name: Restart & Enable  container service
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "rabbitmq.service"
